# Generated by Django 3.1.1 on 2020-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=50)),
                ('business', models.IntegerField()),
                ('antiquity', models.IntegerField()),
                ('loan', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
